name: R-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - r-base=4.3
  - r-renv
  - r-irkernel
  - r-languageserver
  - r-biocmanager
  - fastqc=0.12.1
  - multiqc=1.21
  - cutadapt=4.7
  - samtools=1.1
  - bwa=0.7.17
  - mamba
  - pip
  - pip:
    - pandas
    - scanpy
    - jupyter